import type { NextPage } from "next"
import Head from "next/head"
import { trpc } from "../utils/trpc"

const Home: NextPage = () => {
  const hello = trpc.useQuery(["example.hello", { text: "from tRPC" }])

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="sticky top-0">
        <div className="flex justify-between p-4 max-w-7xl mx-auto">
          <h1 className="font-virgil text-3xl !leading-none mt-1">BalticAds</h1>

          <span className="flex justify-center items-center text-3xl rounded cursor-pointer transition duration-150 ease-out md:hover:bg-gray-200 w-10 pb-[2px]">
            =
          </span>
        </div>
      </div>

      <div className="container flex flex-col items-center justify-center min-h-screen p-10 px-0 mx-auto md:py-20 md:p-10 md:px-0">
        <h1 className="font-extrabold text-center text-7xl font-virgil m-6">
          Visi <span className="text-blue-500">Baltijas</span> sludinājumi
          vienuviet
        </h1>

        <div className="py-6 text-2xl text-blue-500">
          <p>{hello.data ? hello.data.greeting : "Loading.."}</p>
        </div>
      </div>
    </>
  )
}

export default Home
